cabinet/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
import cabinet.views
# Gestion de l'erreur 404

app_name = "cabinet"

urlpatterns = [
    path('', cabinet.views.home, name='homepage'),
        path('fiscalite/', cabinet.views.fiscalite, name='fiscalite'),
         path('comptabilite/', cabinet.views.comptabilite, name='comptabilite'),
        path('juridique/', cabinet.views.juridique, name='juridique'),
        path('management/', cabinet.views.management, name='management'),
            path('blog/', cabinet.views.blog, name='blog'),

    path('blog/categorie/<slug:slug>/', cabinet.views.blog_article, name='blog-categorie'),  # Pour la catégorie sélectionnée

        path('blog/article/<slug:slug>/', cabinet.views.article, name='article'),
path('newsletter/', cabinet.views.newsletter_signup, name='newsletters_signup'),

 
]

# Serve static and media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

compte/urls.py
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
import compte.views
#

# path('',LoginView.as_view(template_name='compte/login.html',
#                           redirect_authenticated=True),
#      name='login'),
# path('logout/',LogoutView.as_view(),name='logout')
app_name= "compte"
urlpatterns = [
    path('login/',compte.views.login_page,name='login'),
    path('logout/',compte.views.logout_user,name='logout'),
    path('delete_account',compte.views.delete_account,name='delete_account'),
    path('profile',compte.views.profile_view,name='profile'),
    path('dashboard/',compte.views.dashboard_admin,name='dashboard'),
    ##ARTICLE
        path('add-article/', compte.views.add_article, name='add_article'),
        path('<slug:slug>/update/', compte.views.article_update, name='update_article'),
        path('<slug:slug>/delete/', compte.views.article_delete, name='delete_article'),
    #CATEGORIE ARTICLE
    path('categorie_article',compte.views.article_categorie,name='article'),
    path('add_categorie_article/',compte.views.add_categorie_article,name='add_categorie_article'),
    path('<slug:slug>/article_categoriedelete/', compte.views.categorie_article_delete, name='delete_categorie_article'),
    path('<slug:slug>/article_categorieupdate/', compte.views.categorie_article_update, name='update_categorie_article'),

#CATEGORIES EXPERTISES
# urls.py
path('gestion/<slug:slug>/', compte.views.expertise_detail, name='expertise_detail'),

path('expertise',compte.views.service_categorie,name='expertises'),
path('<slug:slug>/expertise_delete/', compte.views.expertise_delete, name='delete_expertise'),
path('add_expertise/',compte.views.add_expertise,name='add_expertise'),
path('<slug:slug>/expertise_update/', compte.views.expertise_update, name='update_expertise'),
#SERVICES
path('services/', compte.views.service, name='service'),
path('<slug:slug>/service_update/', compte.views.service_update, name='update_service'),
path('<slug:slug>/service_delete/', compte.views.service_delete, name='delete_service'),
 path('add-service/', compte.views.add_service, name='add_service'),

#MESSAGES
path('contact/', compte.views.contact, name='contact'),
path('confirmation_message/', compte.views.confirm_message, name='confirm_message'),
   path('message/', compte.views.message, name='message'),
   path('<slug:slug>/message_delete/', compte.views.delete_message, name='delete_message'),
path('repondre/<slug:slug>/', compte.views.answer_message, name='repondre_message'),
#CONTACTS
path('contacts/', compte.views.contact_list, name='contact_list'),
path('contacts/add/', compte.views.contact_create, name='contact_create'),
path('contacts/<slug:slug>/delete/', compte.views.contact_delete, name='contact_delete_entreprise'),
path('contacts/<slug:slug>/update/', compte.views.contact_update, name='contact_update_entreprise'),
##
path('newsletter_list/', compte.views.newsletter_list, name='newsletter_list'),
    path('newsletter/delete/<slug:slug>/', compte.views.delete_news, name='delete_news'),

]

site_cabinet/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('cabinet.urls')),
        path("",include('compte.urls')),
            # path('ckeditor/', include('ckeditor_uploader.urls'))
                path("ckeditor5/", include('django_ckeditor_5.urls')),



] +   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cabinet/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from cabinet.models import  News_letter  # Pour utiliser le modèle d'utilisateur personnalisé
from django_ckeditor_5.widgets import CKEditor5Widget
import phonenumbers
from phonenumbers import NumberParseException
class NewsLetterForm(forms.ModelForm):
    class Meta:
        model = News_letter
        fields = ['email',]
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Entrez votre email'}),
        }
        labels = {
            'email': 'Adresse Email',
        }

cabinet/views.py
from pyexpat.errors import messages
from django.shortcuts import get_object_or_404, redirect, render

from cabinet.models import Article, Articlecategorie
from cabinet.forms import NewsLetterForm

# Create your views here.
from django.contrib import messages
from django.db import IntegrityError

def home(request):
    service = Services.objects.all()
    categories_service = expertise.objects.all()
    articles = Article.objects.order_by('-date_publie')[:2]
    categorie_article = Articlecategorie.objects.all()
    heros = HeroImage.objects.filter(page='acceuil').order_by('id')
   
    context = {
        'service': service,
        'categorie_service': categories_service,
        'articles': articles,
        'categorie_article': categorie_article,
        'heros':heros,
    }

    return render(request, 'cabinet/body/index.html', context)
#

def fiscalite(request):
    hero = HeroImage.objects.filter(page='fiscalite').first()

    return render(request,'cabinet/body/fiscalite.html',{'hero':hero})

def juridique(request):
    hero = HeroImage.objects.filter(page='juridique').first()

    return render(request,'cabinet/body/juridique.html',{'hero':hero})
#

def management(request):
    hero = HeroImage.objects.filter(page='management').first()

    return render(request,'cabinet/body/management.html',{'hero':hero})

def comptabilite(request):
    hero = HeroImage.objects.filter(page='comptabilite').first()

    return render(request,'cabinet/body/comptabilite.html',{'hero':hero})
#
def nav(request):
    categories_service=expertise.objects.all()
    print("caaaaa",categories_service)
    context={
        'categorie_service':categories_service
    }
    return render(request,'cabinet/navbar/navbar.html',context)

def blog(request,slug=None):
    hero=HeroImage.objects.filter(page='blog').first()

    article_a_la_une= Article.objects.latest('date_publie') 
    articles_precedents = Article.objects.all().order_by('-date_publie').exclude(slug=article_a_la_une.slug)
    #
    categorie=None
    if slug:
        categorie = Articlecategorie.objects.all()

    context={
            'articles_precedents': articles_precedents,
        'article_a_la_une': article_a_la_une,  # Par exemple
        'categorie':categorie,
        'hero':hero
    }
    return render(request,'cabinet/body/blog.html',context)


# 
def blog_article (request,slug=None):
    hero=HeroImage.objects.filter(page='blog').first()

    article_a_la_une= Article.objects.latest('date_publie') 

    if slug:
        categorie = get_object_or_404(Articlecategorie, slug=slug)


        articles_precedents = Article.objects.filter(article=categorie)

    else:
            # Si aucune catégorie n'est sélectionnée, montrer les articles les plus récents
            articles_precedents = Article.objects.all().order_by('-date_publie').exclude(slug=article_a_la_une.slug)

    #categorie article

    context = {
        'articles_precedents': articles_precedents,
        'article_a_la_une': article_a_la_une,  # Par exemple
        'categorie':categorie,
        'hero':hero,

    }
    return render(request, 'cabinet/body/blog.html', context)
#
from django.http import JsonResponse
from .models import Article, HeroImage, Services, expertise

def article(request, slug=None):
    hero=HeroImage.objects.filter(page='blog').first()

    article= get_object_or_404(Article,slug=slug)
    article_a_la= Article.objects.latest('date_publie') 
    article_a_la_une=None
    if article == article_a_la:
        article_a_la_une=article

        
    context={
        'article':article,
        'articles_precedents': Article.objects.all().order_by('-date_publie').exclude(slug=slug),
        'article_a_la_une':article_a_la_une,
        'hero':hero,
    }
    return render(request,'cabinet/body/category-article.html',context)
##
from urllib.parse import urlparse, urlunparse

def newsletter_signup(request):
    if request.method == 'POST':
        form = NewsLetterForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            try:
                form.save()
                messages.success(request, "✅ Merci pour votre inscription à la newsletter !")
            except IntegrityError:
                messages.error(request, "⚠️ Cette adresse email est déjà inscrite.")
        else:
            if form.errors.get('email'):
                messages.error(request, f"❌ Erreur sur le champ email : {form.errors['email'][0]}")
            else:
                messages.error(request, "❌ Une erreur est survenue. Veuillez vérifier le formulaire.")
    
    # Nettoyer l'URL avant d'ajouter #newsletter
    referer = request.META.get('HTTP_REFERER', '/')
    parsed = urlparse(referer)
    cleaned_url = urlunparse((parsed.scheme, parsed.netloc, parsed.path, '', '', ''))
    return redirect(cleaned_url + '#newsletter')

cabinet/templates/cabinet/navbar/navbar.html
<!-- Upper Navbar -->
{% load static %}

  <!-- Main Navbar -->
  <nav class="navbar  navbar-expand-lg  navbar-custom mt-0 mb-0 py-3 shadow-4" id="mainNavbar" style="background-color: #142f6a">
    <div class="container">
    <div class="d-block">
      <a class="navbar-brand me-2 brand-log-title" href="{{ link }}">
        <img src="{% static '../media/images/LOGO.png' %}" alt="logo">
     
      </a>
      <h6 class="brand-log-title-h6">GROUP CONSULTING OFFICE SARL</h6>
    </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarButtonsExample"
          aria-controls="navbarButtonsExample" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars text-white"></i>
      </button>
      <div class="collapse navbar-collapse ms-5" id="navbarButtonsExample">
        <ul class="navbar-nav mx-auto mb-2 mb-lg-0 nav-menu">
          <li class="nav-item">
            <a class="nav-link nav-link-home text-white fw-bold" href="{% url 'cabinet:homepage' %}">Acceuil</a>
          </li>
<!-- Navbar dropdown -->
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle text-white fw-bold" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Expertises
  </a>
  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
    {% for expertise in categorie_expertise %}
      <li>
        <a class="dropdown-item" href="{% url 'compte:expertise_detail' expertise.slug %}">
          {{ expertise.expertise }}
        </a>
      </li>
    {% endfor %}
  </ul>
</li>
    

          <li class="nav-item">
            <a class="nav-link text-white fw-bold" href="{% url 'cabinet:blog' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white fw-bold" href="{% url 'compte:contact' %}">Contacts</a>
          </li>
          
        </ul>
{% comment %}   
        <div class="d-flex align-items-center ms-auto">
            {% if user.is_authenticated %}
            <a href="{% url 'pro_commerce:dashboard' %}">
                <button class="btn btn-outline-dark custom-outline-button text-lowercase" type="button">Publiez un produit</button>
            </a>
        {% else %}
            <a href="{% url 'compte:login' %}">
                <button class="btn btn-outline-dark custom-outline-button text-lowercase" type="button">Publiez un produit</button>
            </a>
        {% endif %}
        
  
          <a href="#" class="icon-search" aria-label="Search"><i class="fas fa-search fa-2x mx-2"></i></a>
          {% if user.is_authenticated %}
          <div class="dropdown d-inline-block">
              <button class="btn btn-link text-decoration-none dropdown-toggle d-flex align-items-center" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
                  <!-- Cercle avec l'initiale de l'utilisateur -->
                  <div class="user-circle d-flex align-items-center justify-content-center me-2">
                      {{ user.username|slice:":2" }} <!-- Affiche uniquement la première lettre de l'utilisateur -->
                  </div>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <li><a class="dropdown-item" href="{% url 'compte:profile' %}">Profil</a></li>
                  <li><a class="dropdown-item" href="{% url 'pro_commerce:liste_favoris' %}">Liste de favoris</a></li>
                  <li><a class="dropdown-item" href="{% url 'compte:logout' %}">Déconnexion</a></li>
              </ul> 
          </div>
          {% else %}
          <a href="{% url 'compte:login' %}" class="d-inline-block" aria-expanded="false">
              <i class="fas fa-user fa-2x mx-2"></i>
          </a>
          {% endif %}
          
        </div> {% endcomment %}
      </div>
    </div>
  </nav>
  