compte/urls.py
from django.urls import path,include
from django.contrib.auth.views import LoginView,LogoutView
import compte.views
#

# path('',LoginView.as_view(template_name='compte/login.html',
#                           redirect_authenticated=True),
#      name='login'),
# path('logout/',LogoutView.as_view(),name='logout')
app_name= "compte"
urlpatterns = [
    path('login/',compte.views.login_page,name='login'),
    path('logout/',compte.views.logout_user,name='logout'),
    path('delete_account',compte.views.delete_account,name='delete_account'),
    path('profile',compte.views.profile_view,name='profile'),
    path('dashboard/',compte.views.dashboard_admin,name='dashboard'),
    ##ARTICLE
        path('add-article/', compte.views.add_article, name='add_article'),
        path('<slug:slug>/update/', compte.views.article_update, name='update_article'),
        path('<slug:slug>/delete/', compte.views.article_delete, name='delete_article'),
    #CATEGORIE ARTICLE
    path('categorie_article',compte.views.article_categorie,name='article'),
    path('add_categorie_article/',compte.views.add_categorie_article,name='add_categorie_article'),
    path('<slug:slug>/article_categoriedelete/', compte.views.categorie_article_delete, name='delete_categorie_article'),
    path('<slug:slug>/article_categorieupdate/', compte.views.categorie_article_update, name='update_categorie_article'),

#CATEGORIES EXPERTISES
# urls.py
path('gestion/<slug:slug>/', compte.views.expertise_detail, name='expertise_detail'),

path('expertise',compte.views.service_categorie,name='expertises'),
path('<slug:slug>/expertise_delete/', compte.views.expertise_delete, name='delete_expertise'),
path('add_expertise/',compte.views.add_expertise,name='add_expertise'),
path('<slug:slug>/expertise_update/', compte.views.expertise_update, name='update_expertise'),
#SERVICES
path('services/', compte.views.service, name='service'),
path('<slug:slug>/service_update/', compte.views.service_update, name='update_service'),
path('<slug:slug>/service_delete/', compte.views.service_delete, name='delete_service'),
 path('add-service/', compte.views.add_service, name='add_service'),

#MESSAGES
path('contact/', compte.views.contact, name='contact'),
path('confirmation_message/', compte.views.confirm_message, name='confirm_message'),
   path('message/', compte.views.message, name='message'),
   path('<slug:slug>/message_delete/', compte.views.delete_message, name='delete_message'),
path('repondre/<slug:slug>/', compte.views.answer_message, name='repondre_message'),
#CONTACTS
path('contacts/', compte.views.contact_list, name='contact_list'),
path('contacts/add/', compte.views.contact_create, name='contact_create'),
path('contacts/<slug:slug>/delete/', compte.views.contact_delete, name='contact_delete_entreprise'),
path('contacts/<slug:slug>/update/', compte.views.contact_update, name='contact_update_entreprise'),
##
path('newsletter_list/', compte.views.newsletter_list, name='newsletter_list'),
    path('newsletter/delete/<slug:slug>/', compte.views.delete_news, name='delete_news'),

]

site_cabinet/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('cabinet.urls')),
        path("",include('compte.urls')),
            # path('ckeditor/', include('ckeditor_uploader.urls'))
                path("ckeditor5/", include('django_ckeditor_5.urls')),



] +   static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

compte/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import os

from django.utils import timezone
from datetime import timedelta


# Create your models here.
class User(AbstractUser):
    pass

compte/views.py
from pyexpat.errors import messages
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate,logout
from django.conf import settings
from django.views import View

from cabinet.forms import NewsLetterForm
from cabinet.models import Article, Articlecategorie, ContactMessage, HeroImage, News_letter, Services, contact_information, expertise
from compte.models import User
from . import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
#
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import ContactMessageForm


# from dotenv import load_dotenv
from django.utils import timezone
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.core.mail import send_mail
# Create your views here.def login_page(request):
##################


from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import ArticleCategorieForm, ArticleForm, ContactMessageForm, LoginForm, ServiceCategorieForm, ServiceForm, SignupForm, enterprise_contactForm
from django.contrib.auth import login
from django.contrib.auth import get_user_model  # Pour utiliser le modèle d'utilisateur personnalisé
from cabinet import context_processors
#########################
from .mixins import GlobalData
##
    
User = get_user_model()

def login_page(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')

            try:
                print("email:",email)
                # On cherche d'abord un utilisateur ayant cet email
                user = User.objects.get(email=email)
                print("userrr",user)
                # Ensuite, on vérifie que le mot de passe est correct
                user = authenticate(request, username=user.username, password=password)
                
                if user is not None:
                    login(request, user)
                    return redirect('compte:dashboard')  # Redirige vers le tableau de bord après connexion
                else:
                    form.add_error(None, 'Identifiants invalides.')
            except User.DoesNotExist:
                form.add_error(None, "Aucun utilisateur n'est enregistré avec cet email.")
    else:
        form = LoginForm()

    return render(request, 'compte/login.html', {'form': form})

##################
def logout_user(request):
    logout(request)
    
    return redirect('cabinet:homepage')

#profile user
##################
@login_required
def profile(request):
    return render(request,'compte/profile_user.html')

##################
@login_required
def profile_view(request):
    user = request.user
    if request.method == 'POST':
        form = forms.UserProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            user = form.save()
            if form.cleaned_data.get('nouveau_mot_de_passe'):
                update_session_auth_hash(request, user)  # Met à jour la session pour éviter la déconnexion
            # messages.success(request, 'Profil mis à jour avec succès.')
            return redirect('pro_commerce:homepage')
    else:
        form = forms.UserProfileForm(instance=user)
    
    return render(request, 'compte/profile_user.html', {'form': form})

##################
@login_required
def delete_account(request):
    if request.method == 'POST':
        user = request.user
        user.delete()
        messages.success(request, 'Votre compte a été supprimé avec succès.')
        return redirect('pro_commerce:homepage')  # Redirigez vers une page d'accueil ou de connexion après suppression
    return redirect('compte:profile')

##################
#################
def dashboard_admin(request):
    if request.user.is_authenticated:
        
        articles=Article.objects.all().order_by('-date_publie')
    
        context={
        'article':articles
        }
    else:
        return redirect('compte:login')
    return render(request,'compte/admin/admin.html',context)
# #
# def profile(request):
#     return render(request,'compte/profile.html')
@login_required
def profile_view(request):
    user = request.user
    if request.method == 'POST':
        form = forms.UserProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            user = form.save()
            if form.cleaned_data.get('nouveau_mot_de_passe'):
                update_session_auth_hash(request, user)  # Met à jour la session pour éviter la déconnexion
            # messages.success(request, 'Profil mis à jour avec succès.')
            return redirect('compte:dashboard')
    else:
        form = forms.UserProfileForm(instance=user)
    
    return render(request, 'compte/profile_user.html', {'form': form})
#
@login_required
def article_delete(request, slug=None):
    article = get_object_or_404(Article, slug=slug)
    
    if request.method == 'POST':
        article.delete()
        messages.success(request, " L\'article a été supprimé avec succès.")

        return redirect('compte:dashboard')
        
    # Optionally, you can render a confirmation page here if not using a modal
        # return render(request,'compte/admin/admin.html')

    return redirect('compte:dashboard')
#
@login_required
def add_article(request):
    if request.method == 'POST':
        # Initialize the form with POST data and files
        form = ArticleForm(request.POST, request.FILES)
        
        if form.is_valid():
            # Save the main product instance without committing yet
            article = form.save(commit=False)
            article.user = request.user  # Assign the current user
            
            # Save the product instance to the database
            article.save()  # Save product first

          
            
            messages.success(request, " L\'article a été enregistré avec succès.")
            return redirect('compte:dashboard')
        else:
            messages.error(request, "Erreur lors de l\'enregistrement de l\'article Veuillez vérifier les informations.")
    else:
        form = ArticleForm()

    return render(request, 'compte/admin/article/add_article.html', {'form': form})
##
@login_required
def article_update(request, slug=None):
    article = get_object_or_404(Article, slug=slug)
    
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            # Sauvegarde du produit, y compris la photo si un nouveau fichier est téléchargé
            article = form.save(commit=False)
            article.user = request.user  # Assign the current user
            
            # Save the product instance to the database
            article.save()  # Save product first

            messages.success(request, " L\'article a été mis à jour avec succès.")
            return redirect('compte:dashboard')
        else:
            # Ajout de messages d'erreur spécifiques pour le formulaire
            messages.error(request, 'Une erreur s\'est produite. Veuillez vérifier les informations saisies.')
    else:
        form = ArticleForm(instance=article)

    return render(request, 'compte/admin/article/article_update.html', {'form': form})
######################ARTICLE CATEGORIE

def article_categorie(request):
    categorie_article=Articlecategorie.objects.all()
    nombre_categorie_article=categorie_article.count()
    #
    article=Article.objects.all()
    nombre_article=article.count()
    

    context={
        'article':article,
        'categorie_article':categorie_article,
        'nombre_article':nombre_article,
        'nombre_categorie_article':nombre_categorie_article
    }
    return render(request,'compte/admin/article/article_categorie.html',context)
#


    return context
@login_required
def add_categorie_article(request):
    if request.method == 'POST':
        # Initialize the form with POST data and files
        form = ArticleCategorieForm(request.POST)
        
        if form.is_valid():
            # Save the main product instance without committing yet
            categorie_article = form.save(commit=False)
            categorie_article.user = request.user  # Assign the current user
            
            # Save the product instance to the database
            categorie_article.save()  # Save product first

          
            
            messages.success(request, " L\'article a été enregistré avec succès.")
            return redirect('compte:article')
        else:
            messages.error(request, "Erreur lors de l\'enregistrement de l\'article Veuillez vérifier les informations.")
    else:
        form = ArticleCategorieForm()

    return render(request, 'compte/admin/article/add_categorie.html', {'form': form})    
##

@login_required
def categorie_article_delete(request, slug=None):
    article = get_object_or_404(Articlecategorie, slug=slug)
    
    if request.method == 'POST':
        article.delete()
        messages.success(request, " La categorie a été supprimé avec succès.")

        return redirect('compte:article')
        
    # Optionally, you can render a confirmation page here if not using a modal
        # return render(request,'compte/admin/admin.html')

    return redirect('compte:article')
#

@login_required
def categorie_article_update(request, slug=None):
    categorie_article = get_object_or_404(Articlecategorie, slug=slug)
    print("okk")
    if request.method == 'POST':
        form = ArticleCategorieForm(request.POST, request.FILES, instance=categorie_article)
        if form.is_valid():
            # Sauvegarde du produit, y compris la photo si un nouveau fichier est téléchargé

compte/templates/compte/admin/contact/enterprise_contact_list.html
{% extends "../../admin/base.html" %}

<title>{% block title %} Admin page {% endblock %}</title>
{% block main %}

<section class="mb-4">
  <div class="card">
    <div class="card-header text-center py-3">
      <h5 class="mb-0 text-center" id="produit">
        <strong>Contacts</strong>
      </h5>
       {% if messages %} 
       {% for entreprise_contact in messages %}
      <div id="alertMessage">
              <div class="alert {% if entreprise_contact.tags %}alert-{{ entreprise_contact.tags }}{% else %}alert-info{% endif %}" role="alert">
                  {{ entreprise_contact }}
              </div>
      </div>
      {% endfor %}
   {% endif %}
      
    </div>
    <div class="d-flex justify-content-end p-3" id="section-boisson">
        <a href="{% url 'compte:contact_create' %}" class="btn btn-actpagemin">
          <i class="fas fa-plus fa-fw"></i><span class="text-indication-act">Ajouter des infos</span>
        </a>
      </div>
    <div class="card-body">
      {% if entreprise_contact %}
        <div class="table-responsive">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th scope="col">Nom Entreprise</th>
                <th scope="col">Email</th>
                <th scope="col">Numero de telephone</th>
                <th scope="col">Localisation</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              {% for entreprise_contact in entreprise_contact %}
                <tr>

                  <td scope="row">{{ entreprise_contact.nom_entreprise }}</td>
                   
                    <td scope="row">{{ entreprise_contact.email }}</td>

                    <td scope="row">{{ entreprise_contact.numero_telephone }}</td>
                    <td scope="row">{{ entreprise_contact.localisation }}</td>
                  
                  <td>
                    <a href="{% url 'compte:contact_update_entreprise' entreprise_contact.slug %}" class="btn" data-mdb-ripple-init>
                        <i class="fas fa-pencil-alt text-primary fa-1x"></i>
                      </a>
                    
                    <a href="{% url 'compte:contact_delete_entreprise' entreprise_contact.slug%}" class="btn" data-mdb-toggle="modal" data-mdb-target="#modalDelete{{ entreprise_contact.slug }}">
                      <i class="fas fa-trash text-danger fa-1x"></i>
                    </a>

                    <i class="far fa-eye fa-1x text-dark" data-mdb-toggle="modal" data-mdb-target="#modalDetails{{ entreprise_contact.slug }}" style="cursor: pointer;"   ></i>
                  </td>
                </tr>

                <!-- Modal for displaying entreprise_contact details -->
                <div class="modal fade" id="modalDetails{{ entreprise_contact.slug }}" tabindex="-1" aria-labelledby="detailsLabel{{ entreprise_contact.slug }}" aria-hidden="true">
                  <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="detailsLabel{{ entreprise_contact.slug }}">entreprise_contact</h5>
                        <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body text-dark">
                        <h6>Nom: {{ entreprise_contact.nom_entreprise }}</h6>
                        <h6>Email: {{ entreprise_contact.email }}</h6>
                        <h6>Contact: {{ entreprise_contact.numero_telephone }}</h6>
                        <h6>Localisation: {{ entreprise_contact.localisation }}</h6>


                      </div>
                   
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Fermer</button>
                      </div>
                    </div>
                  </div>
                </div>
                
              {% endfor %}
            </tbody>
          </table>
        </div>
      {% else %}
        <p class="text-center">Aucun entreprise_contact.</p>
      {% endif %}
    </div>
  </div>
</section>

<!-- Modal de confirmation de suppression -->
{% for entreprise_contact in entreprise_contact %}
<div class="modal fade" id="modalDelete{{ entreprise_contact.slug }}" tabindex="-1" aria-labelledby="deleteLabel{{ entreprise_contact.slug }}" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header bg-danger">
              <h5 class="modal-title text-white" id="deleteLabel{{ entreprise_contact.slug }}">Confirmer la suppression</h5>
              <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              Êtes-vous sûr de vouloir supprimer cet contact de l'entreprise ?
          </div>
          <div class="modal-footer">
              <form action="{% url 'compte:contact_delete_entreprise' entreprise_contact.slug %}" method="POST">
                  {% csrf_token %}
                  <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Annuler</button>
                  <button type="submit" class="btn btn-danger">Supprimer</button>
              </form>
          </div>
      </div>
  </div>
</div>
{% endfor %} 

{% endblock main %}

compte/templates/compte/admin/contact/enterprise_update_contact.html
{% extends "../../admin/base.html" %} 
{% block header %}
 {{ form.media }} 
 {% endblock header %} 
 {% load form_helpers %} 
 {% block main %}
<div class="container mt-5 d-flex justify-content-center">
  <div class="card shadow p-4 w-100" style="max-width: 800px">
    <h4 class="text-center mb-4">Mettre à jour les infos de l'entreprise</h4>

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      <!-- Ligne 1 : nom entreprise + contact -->
      <div class="row mb-3">
        <div class="col-md-6">
          <div class="form-group">
            <label
              for="{{ form.nom_entreprise.id_for_label }}"
              class="form-label text-muted"
              >{{ form.nom_entreprise.label }}</label
            >
            {{ form.nom_entreprise }} {% if form.nom_entreprise.errors %}
            <div class="invalid-feedback d-block">
              {% for error in form.nom_entreprise.errors %}
              <p>{{ error }}</p>
              {% endfor %}
            </div>
            {% endif %}
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <label
              for="{{ form.numero_telephone.id_for_label }}"
              class="form-label text-muted"
              >{{ form.numero_telephone.label }}</label
            >
            {{ form.numero_telephone }} {% if form.numero_telephone.errors %}
            <div class="text-danger">
              {% for error in form.numero_telephone.errors %}
              <p>{{ error }}</p>
              {% endfor %}
            </div>
            {% endif %}
          </div>
        </div>
      </div>

      <!-- Ligne 2 : numéro téléphone + email -->
      <div class="row mb-3">
       

        <div class="col-md-6">
          <div class="form-group">
            <label
              for="{{ form.email.id_for_label }}"
              class="form-label text-muted"
              >{{ form.email.label }}</label
            >
            {{ form.email }} {% if form.email.errors %}
            <div class="text-danger">
              {% for error in form.email.errors %}
              <p>{{ error }}</p>
              {% endfor %}
            </div>
            {% endif %}
          </div>
        </div>
      {% comment %} </div> {% endcomment %}

      <!-- Ligne 3 : localisation seule (pleine largeur) -->
      {% comment %} <div class="row mb-4"> {% endcomment %}
        <div class="col-md-6">
          <div class="form-group">
            <label
              for="{{ form.localisation.id_for_label }}"
              class="form-label text-muted"
              >{{ form.localisation.label }}</label
            >
            {{ form.localisation }} {% if form.localisation.errors %}
            <div class="text-danger">
              {% for error in form.localisation.errors %}
              <p>{{ error }}</p>
              {% endfor %}
            </div>
            {% endif %}
          </div>
        </div>
      </div>

      <!-- Boutons -->
      <div class="text-center">
        <button type="submit" class="btn btn-primary">Enregistrer</button>
        <a href="{% url 'compte:contact_list' %}" class="btn btn-secondary"
          >Annuler</a
        >
      </div>
    </form>
  </div>
</div>
{% endblock main %}

compte/templates/compte/admin/contact/message_contact.html
{% extends "../../admin/base.html" %}

<title>{% block title %} Admin page {% endblock %}</title>
{% block main %}

<section class="mb-4">
  <div class="card">
    <div class="card-header text-center py-3">
      <h5 class="mb-0 text-center" id="produit">
        <strong>Messages</strong>
      </h5>
       {% if messages %} 
       {% for message in messages %}
      <div id="alertMessage">
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}" role="alert">
                  {{ message }}
              </div>
      </div>
      {% endfor %}
   {% endif %}
      
    </div>
    <div class="card-body">
      {% if message %}
        <div class="table-responsive">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th scope="col">Date envoi</th>

                <th scope="col">Nom Prenom</th>
                <th scope="col">Email</th>
                <th scope="col">Numero de telephone</th>
                <th scope="col">Objet</th>
                <th scope="col">Contenu</th>
                <th scope="col">Repondu ?</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              {% for message in message %}
                <tr>
                  <td scope="row">{{ message.date_envoi }}</td>

                  <td scope="row">{{ message.nom }}</td>
                   
                    <td scope="row">{{ message.email }}</td>

                    <td scope="row">{{ message.numero_telephone }}</td>
                    <td scope="row">{{ message.objet }}</td>
                    <td scope="row">{{ message.contenu }}</td>
                    <td scope="row">
                      {% if message.repondu %}
                        <i class="fas fa-check-circle text-success" title="Répondu"></i>
                      {% else %}
                        <i class="fas fa-times-circle text-danger" title="Non répondu"></i>
                      {% endif %}
                    </td>
                  <td>
                  {% if not message.repondu %}
                    <a href="#" class="btn" data-mdb-toggle="modal" data-mdb-target="#modalReply{{ message.slug }}">
                      <i class="fas fa-reply text-primary fa-1x" title="Repondre"></i>
                    </a>
                    {% endif %}
                    <a href="#" class="btn" data-mdb-toggle="modal" data-mdb-target="#modalDelete{{ message.slug }}">
                      <i class="fas fa-trash text-danger fa-1x"></i>
                    </a>

                    <i class="far fa-eye fa-1x text-dark" data-mdb-toggle="modal" data-mdb-target="#modalDetails{{ message.slug }}" style="cursor: pointer;"   ></i>
                  </td>
                </tr>

                <!-- Modal for displaying message details -->
                <div class="modal fade" id="modalDetails{{ message.slug }}" tabindex="-1" aria-labelledby="detailsLabel{{ message.slug }}" aria-hidden="true">
                  <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="detailsLabel{{ message.slug }}">Message</h5>
                        <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <h6>Nom: {{ message.nom }}</h6>
                        <h6>Email: {{ message.email }}</h6>
                        <h6>Objet: {{ message.objet }}</h6>

                      </div>
                   
                      <div class="modal-body">
                        <h6>Contenu: {{ message.contenu }}</h6>
                      
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Fermer</button>
                      </div>
                    </div>
                  </div>
                </div>
                <!--modal for answer a message -->
                <div class="modal fade" id="modalReply{{ message.slug }}" tabindex="-1" aria-labelledby="replyLabel{{ message.slug }}" aria-hidden="true">
                  <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                      <form method="POST" action="{% url 'compte:repondre_message' message.slug %}">
                        {% csrf_token %}
                        <div class="modal-header bg-respmessuse text-white">
                          <h5 class="modal-title" id="replyLabel{{ message.slug }}">Répondre à {{ message.nom }}</h5>
                          <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                          <div class="mb-3">
                            <label class="form-label">Email</label>
                            <input type="email" class="form-control" value="{{ message.email }}" readonly>
                          </div>
                          <div class="mb-3">
                            <label class="form-label">Réponse</label>
                            <textarea name="reponse" class="form-control" rows="5" placeholder="Tapez votre réponse ici..." required></textarea>
                          </div>
                        </div>
                        <div class="modal-footer">
                          <button type="submit" class="btn bg-respmessuse text-white">Envoyer</button>
                          <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Annuler</button>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
                
              {% endfor %}
            </tbody>
          </table>
        </div>
      {% else %}
        <p class="text-center">Aucun message.</p>
      {% endif %}
    </div>
  </div>
</section>

<!-- Modal de confirmation de suppression -->
{% for message in message %}
<div class="modal fade" id="modalDelete{{ message.slug }}" tabindex="-1" aria-labelledby="deleteLabel{{ message.slug }}" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header bg-danger">
              <h5 class="modal-title text-white" id="deleteLabel{{ message.slug }}">Confirmer la suppression</h5>
              <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              Êtes-vous sûr de vouloir supprimer cet message ?
          </div>
          <div class="modal-footer">
              <form action="{% url 'compte:delete_message' message.slug %}" method="POST">
                  {% csrf_token %}
                  <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Annuler</button>
                  <button type="submit" class="btn btn-danger">Supprimer</button>
              </form>
          </div>
      </div>
  </div>
</div>
{% endfor %} 

{% endblock main %}